# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml
[hyprland]
cursor_size = 32
cursor_theme = "Simp1e-breeze-snow"
document_font_size = 10
explorer = "thunar"
font = "Google Sans"
font_size = 10
gtk_theme = "Kripton"
icon_theme = "Newaita-reborn"
monospace_font = "PaperMono Nerd Font Mono"
monospace_font_size = 9
notifications = "dunst"

[notification]
font = "Google Sans"
font_size = 10

[qt5] 
font = "Google Sans"
font_size = 10
monospace_font = "PaperMono Nerd Font Mono"
monospace_font_size = 9

[qt6] 
font = "Google Sans"
font_size = 10
monospace_font = "PaperMono Nerd Font Mono"
monospace_font_size = 9

[rofi]
font = "PaperMono Nerd Font Mono"

[rofi.websearch]
font = "PaperMono Nerd Font Mono"

[rofi.bookmarks]
font = "PaperMono Nerd Font Mono"

[waybar]
font = "PaperMono Nerd Font Mono"

[weather]
time_format = "12h"
